### ISSUE TITLE
Add npm scripts

### ISSUE THREAD

**Issue by lejoe** [ginetta/skeleton#100]
npm start -> gulp
npm build -> gulp build
npm test -> gulp test
npm serve -> gulp serve
npm deploy -> gulp deploy
?

unkowns (to test):
- errorhandling
- env arguments passed to the command

**Comment by lejoe** [comment]
I'm fine with this change as long that on skeleton we keep gulp as the go to solution for scripts.

What I don't want to end up with is a different solution for each scripts.
I see the advantage for compatibility and adaptation on per project basis.
My only requirement for the skeleton is that if something is doable (reasonably) with gulp we implement it with that.

**Comment by peterbraden** [comment]
I'm alright with gulp being the default method, but I also don't want to end up with shell scripts ported to gulp for no reason other than 'consistency' - ie, doing gulp.task('foo', shell('bar')) instead of just calling bar.

The deployment for example.

**Comment by lejoe** [comment]
Right if shell in your example is only one pipe and 'foo' is isolated (no dependencies on other tasks).

**Comment by peterbraden** [comment]
I mean something like this: https://github.com/ginetta/dashboard/blob/master/package.json#L54

**Comment by meodai** [comment]
@peterbraden  sounds good to me
