### ISSUE TITLE
BUG: skeleton not working when installing from scratch

### ISSUE THREAD

**Issue by lejoe** [ginetta/skeleton#105]
There is probably a module dependency missing (glob) and with some node version the npm scripts are not running (seen on snap-ci).

**Comment by lejoe** [comment]
Not more info for now. Needs investigation.
Noticed after @meodai told me

**Comment by meodai** [comment]
and I noticed after @diluno told me

**Comment by lejoe** [comment]
Regarding the node versions, this is part of the problem:
```github:gulpjs/gulp-cli#4.0  should be git://github.com/gulpjs/gulp-cli#4.0```

**Comment by getflourish** [comment]
Just had the same problem, because I was missing "glob".
