### ISSUE TITLE
Does our icon sprite with <use> work on ie9-11?

### ISSUE THREAD

**Issue by lejoe** [ginetta/skeleton#150]
I've seen other website using https://github.com/Keyamoon/svgxuse to make that work which make me wonder if we need it too?

**Comment by lucalanca** [comment]
We need a polyfill to make it work. On the portfolio site we used https://github.com/jonathantneal/svg4everybody which does the trick.

**Comment by lejoe** [comment]
Ok, let's include it then as the way it is currently it doesn't work
