### ISSUE TITLE
Custom Sass Mixins and Functions

### ISSUE THREAD

**Issue by lucalanca** [ginetta/skeleton#19]
Where is the best location to put them? I think we should create two folders within app/css for this:

app
├─css
         ├─mixins
                   ├─_mixins.scss
         ├─functions
                   ├─_functions.scss
├─_0.settings.scss
├─_1.base.scss

and including this files **before** the project-specific files. What do you think?

**Comment by lejoe** [comment]
Closing this as it was aimed towards the first version.
We'll address separately in [v2](https://github.com/ginetta/skeleton/tree/v2/master).
