### ISSUE TITLE
Optimize Assets

### ISSUE THREAD

**Issue by lucalanca** [ginetta/skeleton#2]
- [x] remove the bower_components forlder
- [x] Optimize css files for production (minification, gzip)
- [ ] Optimize js files for production (concat requirejs modules, gzip)
- [x] Optimize page html files for production (minification)
- [x] Optimize images
- [x] Optimize svgs
- [ ] Assets versioning (for caching purposes)
- [ ] Experiment with above the fold css [grunt-penthouse](https://www.npmjs.org/package/grunt-penthouse)

**Comment by lejoe** [comment]
Closing this as it was aimed towards the first version.
We'll address separately in [v2](https://github.com/ginetta/skeleton/tree/v2/master).
