### ISSUE TITLE
Javascript Modules

### ISSUE THREAD

**Issue by lucalanca** [ginetta/skeleton#33]
I decided to create this issue to discuss how we define and pack javascript modules. Currently we use AMD modules with require.js. However, this has been complex in production code, since the require config is different depending on the path of the file.

I think this is a good opportunity to discuss if using require.js is the best option.

Alternatives:
— CommonJS modules via browserify or Melchior.js (http://pixelhunter.me/post/98247138509/getting-started-with-melchior-js)
— ES6 Modules (available today via a polyfill)

**Comment by lejoe** [comment]
Closing this as it was aimed towards the first version.
We are reconsidering for the 2nd version and trying out solutions on different projects.
