### ISSUE TITLE
Styleguide generator

### ISSUE THREAD

**Issue by lucalanca** [ginetta/skeleton#4]
Each project should have an automatically generated styleguide with the following:
- List of components
- For each component, the documentation of the component (name, description, version, author, how to use it)
- List of SASS utilities (mixins, functions, classes)
- Base styling description (fonts, colors variables, spacing variables, etc)

Please feel free to discuss this here :saxophone:

**Comment by lejoe** [comment]
Closing this as it was aimed towards the first version.
We'll address separately in [v2](https://github.com/ginetta/skeleton/tree/v2/master).
