### ISSUE TITLE
jit-grunt error

### ISSUE THREAD

**Issue by meodai** [ginetta/Skeleton#50]
after a fresh pull from the master and NPM install I get:

jit-grunt: Plugin for the "js" task not found.
If you have installed the plugin already, please setting the static mapping.
See https://github.com/shootaroo/jit-grunt#static-mappings

Warning: Task "js:dev" not found. Use --force to continue.

Aborted due to warnings.

**Comment by lejoe** [comment]
I've got a feeling it has nothing to do with jit-grunt but is related to @lucalanca js tasks changes.
We might have forgotten one of these:
https://github.com/ginetta/Skeleton/commit/ddfb0d88932957e9ad69d2599af5aac9883375d0

**Comment by lucalanca** [comment]
I think we might have one on the watchers. Will look into those.
