### ISSUE TITLE
mergeDefaultOptions ignores passed options if not defined in yml

### ISSUE THREAD

**Issue by meodai** [ginetta/skeleton#68]
options that are passed to a mixin that are not defined in the yml file are ignored.
since the '_.forEach(optionsSchema)' loops the yml ignoring the actual passed options

**Comment by lucalanca** [comment]
I think this is actually a good default.

**Comment by lejoe** [comment]
+1
If we take the time to define an API/schema (definition) for each module it should be complete
I'm ok with the &attributes being an exception to pass context classes as it's basically a jade thing
