### ISSUE TITLE
Solve the branches mess

### ISSUE THREAD

**Issue by lejoe** [ginetta/skeleton#80]
Move v2/master to master.
(think about what will happen to the open PRs)

**Comment by peterbraden** [comment]
So my plan is as follows:

- Merge v2/master -> master
- go through PR's #74 #64 #63 #59 #57 #54 and make sure they now track master.

**Comment by lejoe** [comment]
+1
AFAIK for your point two you will have to open new PRs as you can't modify the tracking after they are opened. Maybe it will work magically though.

**Comment by peterbraden** [comment]
#74 is now #87 
#64 is now #88
#63 is now #89
#59 is still #59 
#57 is now #90
#54 is now #91
